### ISSUE TITLE
the RML output misses csvw:dialect property

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/LDWizard-HelloWorld#2]
The RML output misses the csvw:dialect property definition like:   

csvw:dialect [ 
      a csvw:Dialect;
      csvw:delimiter ";"
 ]

This is leads to problems with running the out of the box rmlmapper from https://github.com/RMLio/rmlmapper-java

**Comment by thomasdegroot18** [comment]
Voor de meeste csv's die standardscompliant zijn zal de dialect property voor RML niet nodig zijn. 
Maar voor een groot aantal Nederlandse csv's zal dat wel het geval zijn. Hierdoor kan het dus zijn dat deze csv's niet goed ingelezen worden door de RMLmapper. Voor CoW nemen het dialect al mee, en dat zou ook voor RML kunnen.

We gaan dit issue meenemen in het RML transformatie script.

**Comment by GerwinBosch** [comment]
Fixed in https://github.com/netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard/commit/c464dcebebdc01cdbcd83aa189df48dd1f879d7c
