### ISSUE TITLE
export transformation output

### ISSUE THREAD

**Issue by ivozandhuis** [netwerk-digitaal-erfgoed/LDWizard-HelloWorld#3]
Hier komt (nog?) geen TriG uit, maar n-triples.

**Comment by wouterbeek** [comment]
Een beetje sneaky: N-Triples is altijd TriG :-)  Maar de file extensie moet nog `.trig` worden.

**Comment by GerwinBosch** [comment]
De file extensie is voor de getransformeerde data is `.trig`
